apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app
  name: app
spec:
  containers:
    - image: david13356/otel-example:latest
      name: app
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "opentelemetrycollector:4317"
        - name: RETURN_ERROR
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: app
  type: LoadBalancer
