apiVersion: v1
kind: Pod
metadata:
  labels:
    run: zipkin
  name: zipkin
spec:
  containers:
    - image: openzipkin/zipkin
      name: zipkin

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  ports:
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    run: zipkin
  type: LoadBalancer
